### ISSUE TITLE
"Error: invalid total win" when moving player to EndWidget

### ISSUE THREAD

**Issue by lieuzhenghong** [nodeGame/nodegame#115]
Description of issue
===============

The total win is not calculated correctly 

![image](https://user-images.githubusercontent.com/7903071/72265310-466fad00-3657-11ea-8b74-3571c6e98093.png)

**Expected output:** Total win 0.00 USD
**Actual output:** Error

Reproducing the bug 
===============

1. Clone my communication game [here](https://github.com/lieuzhenghong/communication-game). 
2. Start the server with `node launcher.js --default communication-game`.
3. Open up two windows to `localhost:8080`.
4. Once both players have connected and the game has started, disconnect a player (just close the window)

Other information
===============

**Comment by shakty** [comment]
Thanks for posting this reproducible example. The EndScreen is expecting a winning striclty greater than 0. This is not as it should be, will fix asap.

**Comment by shakty** [comment]
Fixed in master. Now there is no constraint, meaning that even negative bonus are allowed.

**Comment by lieuzhenghong** [comment]
No problems at all. Thanks for fixing it so quick. You said you fixed it in master, but the last commit was three days ago, so I'm not sure what I should be `git pull`ing...?

**Comment by shakty** [comment]
Forgot to push...now it is up https://github.com/nodeGame/nodegame-widgets

**Comment by shakty** [comment]
Fixed in 5.7.0
