### ISSUE TITLE
Eternal "Waiting for player" overlay when at EndWidgets screen after a successful game

### ISSUE THREAD

**Issue by lieuzhenghong** [nodeGame/nodegame#116]
Description of issue
===============

After a successful game, players are taken to the End Screen. After a few seconds later, the "Waiting for other players to be done..." overlay pops up and doesn't go away.

![image](https://user-images.githubusercontent.com/7903071/72266184-d19d7280-3658-11ea-9d2f-374baaeeccaa.png)

Reproducing the bug 
===============

1. Clone my communication game [here](https://github.com/lieuzhenghong/communication-game). 
2. Start the server with `node launcher.js --default communication-game`.
3. Open up two windows to `localhost:8080`.
4. Play the game normally with two players.
5. After a few seconds, the overlay will appear and won't go away.

Other information
===============

- This bug doesn't occur when one player has disconnected and the other is brought to the end screen.
- I've tried clearing the cache like you suggested but this bug still occurs.

**Comment by shakty** [comment]
Thanks, in your receive step you have a setTimeout calling node.done after 20 seconds. That is fired during the end step causing the behavior you observe. I am closing this as this is not a nodeGame bug.

**Comment by lieuzhenghong** [comment]
Ah, I should have cleared the timeout on exit. Thanks for catching that!
