### ISSUE TITLE
Blank page when loading game from different folder

### ISSUE THREAD

**Issue by lieuzhenghong** [nodeGame/nodegame#126]
Dear Stefano,

Sorry to bother but I don't have any idea how to debug this.

As you know I've taken the game folder out of the nodegame-v5.xx folder for easier version control/deployment. But this has introduced a host of new errors.

Right now, when i click Communication Game, I get taken to a blank page. I've looked at the browser console and get the following output:

```
Navigated to http://localhost:8080/communication-game/
ng@0.0.0 - 18:1:17:499 > warn - Socket.disconnect: socket is not connected nor connecting. Try with force parameter. nodegame-full.js:29012:21
This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”. communication-game
ng@0.0.0 - 18:1:17:860 > silly - ee.game removed listener: REALLY_DONE nodegame-full.js:29012:21
ng@0.0.0 - 18:1:17:861 > silly - ee.game removed listener: STEPPING nodegame-full.js:29012:21
ng@0.0.0 - 18:1:17:861 > silly - ee.game removed listener: PLAYING nodegame-full.js:29012:21
ng@0.0.0 - 18:1:17:861 > silly - ee.game removed listener: PAUSED nodegame-full.js:29012:21
ng@0.0.0 - 18:1:17:862 > silly - ee.game removed listener: RESUMED nodegame-full.js:29012:21
ng@0.0.0 - 18:1:17:863 > silly - game.on: added: REALLY_DONE nodegame-full.js:29012:21
ng@0.0.0 - 18:1:17:863 > silly - game.on: added: STEPPING nodegame-full.js:29012:21
ng@0.0.0 - 18:1:17:864 > silly - game.on: added: PLAYING nodegame-full.js:29012:21
ng@0.0.0 - 18:1:17:864 > silly - game.on: added: PAUSED nodegame-full.js:29012:21
ng@0.0.0 - 18:1:17:864 > silly - game.on: added: RESUMED nodegame-full.js:29012:21
ng@0.0.0 - 18:1:17:865 > silly - node-window: inited. nodegame-full.js:29012:21
ng@0.0.0 - 18:1:17:866 > info - connecting to http://localhost:8080/communication-game. nodegame-full.js:29012:21
Source map error: Error: request failed with status 404
Resource URL: http://localhost:8080/stylesheets/nodegame.css
Source Map URL: nodegame.css.map

ng@0.0.0 - 18:1:27:871 > warn - connection attempt to http://localhost:8080/communication-game timed out. Disconnected.
```

There seems to be a Source map error (nodegame.css inaccessible). But the file is accessible, and when I click "Ultimatum game" (present in the `nodegame-v5.xx` folder), there is no problem loading `localhost:8080/stylesheets/nodegame.css`.

**Comment by shakty** [comment]
Hi,

You may get a blank page if there is a mismatch between the name of the
channel between client and server.

The name of the channel is set in channel/channel.settings.js, endpoint
option or playerServer option. It is usually equal to the name of the game,
but it can be changed to anything.

Please check if that matches the value of channel inside file
public/js/index.js. The channel is the parameter inside the method
node.connect(). If there is no parameter, then the value is extracted from
the address, but it might fail, for example, if you run your game as a
default game. So just speficy it. If your channel is called 'abc', then you
need to write: node.connect('/abc').

Let me know if it helps.

Stefano

Lieu Zheng Hong <notifications@github.com> schrieb am Sa., 22. Feb. 2020,
19:08:

**Comment by lieuzhenghong** [comment]
Hi Stefano,

It's actually the other way round. When I type `node launcher.js --default communication-game`, it works. But when I do not specify a default, then it does not work.

Even after explicitly specifying `node.connect('/communication-game');` in public/index.js and `name: 'communication-game' ` in `module.exports` of `channel.settings.js`, it does not work.

**Comment by shakty** [comment]
You should specify the "endpoint" not the "name." Currently, in
https://github.com/lieuzhenghong/communication-game/blob/master/channel/channel.settings.js
endpoint
is empty, try to change it to the same channel name you use in the
node.connect command.

Am Sa., 22. Feb. 2020 um 20:17 Uhr schrieb Lieu Zheng Hong <
notifications@github.com>:

**Comment by shakty** [comment]
Just to clarify, endpoint is inside the playerServer object.

Am Sa., 22. Feb. 2020 um 21:38 Uhr schrieb Stefano Balietti <
futur.dorko@gmail.com>:

**Comment by lieuzhenghong** [comment]
Ah, thanks for the clarification. That did the trick.
