### ISSUE TITLE
Widgets.get: Slider not found

### ISSUE THREAD

**Issue by lieuzhenghong** [nodeGame/nodegame#128]
I tried to use the new Slider widget but get `Error: Widgets.get: Slider not found.`, `ng@5.1.1 - 18:12:12:243 > error - 5.1.1@18:12:12> http://localhost:8080/javascripts/nodegame-full.js 39620,19: Error: Widgets.get: Slider not found`

This is using nodegame v5.8.1.

You can `git clone` the `belief-elicitation` branch of `communication-game` [here](https://github.com/lieuzhenghong/communication-game/tree/belief-elicitation) and run the experiment until the belief step.

```
      const slider_box_1 = W.getElementById("slider_box_1")
      var slider = node.widgets.append('Slider', slider_box_1, {
        mainText: "Out of 100 people (50 pairs) who were not chosen to send a message, how many will play A?",
        id: 'slider_1',
        initialValue: 0,
        required: true,
      })
```

**Comment by shakty** [comment]
To use the Slider you need to update to the latest development version. If you did already, you need to make sure that your browser is not caching the previous version of nodeGame, so try your game in private mode. Let me know.

**Comment by lieuzhenghong** [comment]
I have downloaded the latest version of `nodegame-installer.js`, run `node nodegame-installer.js` to install v5.8.1 and run in private browsing mode, but still not working. Is there a different installer I should be using to install the latest dev version? And will I be able to deploy it on DigitalOcean?

**Comment by shakty** [comment]
The right command is:

nodegame-installer.js @dev

However, it is maybe easier to just git pull the nodeGame modules:

- Go inside node_modules/nodegame-server and type: git pull
- Go inside node_modules/nodegame-widgets and type: git pull

On Digital Ocean, you will need to manually do git pull to be able to run
the Slider (until I publish the new update).





Am So., 23. Feb. 2020 um 22:17 Uhr schrieb Lieu Zheng Hong <
notifications@github.com>:

**Comment by lieuzhenghong** [comment]
Both of them say that they're up to date, but I still get the same error...

**Comment by lieuzhenghong** [comment]
Trying @dev now

**Comment by lieuzhenghong** [comment]
Using the dev version worked! But this won't work when I use the DigitalOcean deploy, right?

**Comment by shakty** [comment]
On Digital Ocean, you will have to do git pull as described before.

Am So., 23. Feb. 2020 um 22:49 Uhr schrieb Lieu Zheng Hong <
notifications@github.com>:

**Comment by lieuzhenghong** [comment]
Hi @shakty , the thing is that on nodegame-v5.8.1 (not dev), `git pulling` gives "Everything up-to-date" but it still doesn't work. I had to use `node nodegame-installer.js @dev` in order for it to work.

**Comment by shakty** [comment]
Once you are on @dev you can use git pull. Digital Ocean uses a stable @dev version
