### ISSUE TITLE
Two issues with slider: doesn't save in data.json, and difficult to tell it is a slider

### ISSUE THREAD

**Issue by lieuzhenghong** [nodeGame/nodegame#129]
The slider widget doesn't look like a slider because there is no background bar. It looks like a button and might confuse users:

![image](https://user-images.githubusercontent.com/7903071/75120842-8f6b4600-5686-11ea-8bcc-8135ddb1dba5.png)

There should be a background bar like so:

![image](https://user-images.githubusercontent.com/7903071/75120891-fc7edb80-5686-11ea-99f9-baa12ac8b219.png)

Also, at the end step, I don't think the slider widget is logging any data. At least, I don't see it in data.json.

**Comment by lieuzhenghong** [comment]
I don't have to use a slider right now; I can use a input box instead if this feature is too experimental, and you want to focus on other features right now.

**Comment by shakty** [comment]
Thanks for the feedback.

You can change the type of visualization of the slider with the type:
'flat' option and have the background (maybe that should be the default?).

Regarding not saving the data, that is weird, I will double check tomorrow.

I plan to release a new version of nodeGame with the Slider by the end of
the week, it will take a few days more to have it on Digital Ocean.

Am So., 23. Feb. 2020 um 22:57 Uhr schrieb Lieu Zheng Hong <
notifications@github.com>:

**Comment by lieuzhenghong** [comment]
Thanks for pointing out the 'flat' option! One more issue: Even when I choose `required: true`, I don't have to move the slider away from its default position at all and can click 'Done' anyway.
