### ISSUE TITLE
create-game script fails on windows 6.0.1

### ISSUE THREAD

**Issue by jjensenius3** [nodeGame/nodegame#146]
node nodegame create-game  fails to complete on a fresh install of 6.0.1 on windows
throws the error:
Error: ENOENT: no such file or directory, stat '-i've-removed-my-path-\nodegame-v6.0.1\node_modules\nodegame-game-template\private\.gitkeep'

**Comment by shakty** [comment]
Hi John, Thanks for finding the first bug of V6!

I have admit it was not too difficult. Apparently, something has changed in the way npm handles its index and, even if they are identical, the stable version has this bug and the development version has not.

I am patching asap, in the meantime people can work on the development version

    node nodegame-installer @dev

**Comment by shakty** [comment]
This is now fixed in 6.0.2. Thanks again for reporting!
