### ISSUE TITLE
When accessing game concurrently with different authenticated users, one of the accesses is invalid

### ISSUE THREAD

**Issue by chengemily** [nodeGame/nodegame#160]
Currently, when we click on e.g. the two below links in rapid succession, the first link clicked gains access to the game, and the other link sees an error saying the user is "already in the room". Both users are authenticated. When clicking the two links with some time in between, everything works perfectly. 

http://localhost:8080/game-name/auth/userA/?startingRoom=room1
http://localhost:8080/game-name/auth/userB/?startingRoom=room1

This is the error displayed: `error: ServerChannel.placeClient: player already in room: "room1" name=game-name`

After some logging, we notice that in `SocketIO.js` line 138 the `nodegame-token` attribute in `socket.handshake` is equal for both accesses. Then, this `nodegame-token` is used later on in `GameServer.onConnect` to get the `clientId`, which is again equal for both cases. Finally, when the second user tries to connect, the server sees that `clientId` already in the starting room and refuses the second user. 

How can we fix this? Thanks!

**Comment by shakty** [comment]
Hi,

If I understand you correctly, this happens only if you try to access those links from the same browser. Can you confirm?

If so, there is a auth cookie set, so when the second connection arrives to the server, nodeGame reads the cookie of the first one, so it is recognized as the first player. I am not sure why it works when you wait some time in between, are you sure the first player isn't disconnected?

Can you confirm this is the use case you really need (i.e., two authenticated users from the same browser)? If so, I am not sure this is fixable, but I can try to find out a solution.

**Comment by shakty** [comment]
Hi, is this still an issue or can I close it?

**Comment by chengemily** [comment]
No longer an issue! Thanks for your helpful response.
