### ISSUE TITLE
Clarification on documentation for SYNC_STAGE 

### ISSUE THREAD

**Issue by chengemily** [nodeGame/nodegame#166]
Hi, I'm having trouble implementing `SYNC_STAGE` following the Synchronization documentation. I have a stage with multiple steps for which I want `SYNC_STAGE`, then for the rest of the game I would like `SYNC_STEP`. So far, I have set the default step rule to be `SYNC_STEP` in the logic and did not change the default step rule from `WAIT` in the player. Then, I extended the specific stage to have `stepRule: stepRules.SYNC_STAGE` in both `player.js` and `logic.js`. However, once both players reach the end of the stage and press `Done`, they cannot advance as the logic has not advanced past the first step. The documentation says that for `SYNC_STAGE`, the players wait for a message from the server to step-- however, I couldn't find how to send this message. Any advice? Thanks!

**Comment by shakty** [comment]
Hi,

his is a feature not used often, since [levels](Levels-v6) have been introduced, so the API needs some refactor and the doc is a bit outdated.

To begin with pull the latest  nodegame-client, or install latest dev, otherwise an error will be raised.

Say you have a stage with three steps, you can do the following:

In player.js:

```js
    stager.extendStep('step1', {
        stepRule: stepRules.SOLO,
    });

    stager.extendStep('step2', {
        stepRule: stepRules.SOLO,
    });

    stager.extendStep('step3', {
        stepRule: stepRules.WAIT,
    });
```


In logic.js

```js
    stager.extendStep('step1', {
        stepRule: stepRules.OTHERS_SYNC_STAGE,
        cb: function() {
            // Prevents to go to next step, instead goes to next stage.
            node.game.breakStage(true);
        }
    });
```

It is a bit cumbersome, but it will work.

**Comment by shakty** [comment]
I have updated the doc, it should be clearer now. There is a warning that the API is in refactor and it may change in the next release.

**Comment by shakty** [comment]
Can I close?

**Comment by chengemily** [comment]
Great! Thank you! It works.
