### ISSUE TITLE
Visual Timer Widget bug on level change

### ISSUE THREAD

**Issue by TVGG** [nodeGame/nodegame#169]
If the client side has a visual timer in the header (W.generateHeader()) the client will crash on level change. The player will still be on the next level waiting room but they get kicked once a game starts due to being unresponsive (ping request).

For the moment a work around would be to delete the visual timer before changing to a new level.

**Comment by shakty** [comment]
Thanks for your bug report @TVGG ! 

This is actually happening any time `game.stop()` is invoked with a running VisualTimer. The bug is now fixed in v7. As you suggest, for v6 one should manually destroy the timer before game.stop is invoked (or new level is started).
