### ISSUE TITLE
PLAYER_SORTING in Waiting-room wiki DOC is wrong

### ISSUE THREAD

**Issue by TVGG** [nodeGame/nodegame#170]
In the documentation it says that the PLAYER_SORTING function runs if connected players is > group_size. This is not the case always the case. Looking at the code of WaitingRoom.js (server) on line 1350 it only runs if nPlayersToDispatch > groupSize. It is possible to have nPlayersToDispatch ==groupSize but nPlayers> groupSize.

To replicate:
-In waitroom.settings.js
GROUP_SIZE:2,
POOL_SIZE:3

-Then connect 3 players

**Comment by shakty** [comment]
That is strictly correct, however I still don't see the practical difference. It is always the case that the number of connected player is larger than group size if the number of players to dispatch is larger than group size AND a dispatch is happening (see line 1340). Am I missing something?

**Comment by TVGG** [comment]
Here is some clarification.  The initial post has been edited to better reflect the issue.

Line 1340:
This code runs when game are dispatched and not enough players are connected to fill them. It logs a message

Line 1350:
This code runs when we need to dispatch more than 1 game.

Line 1404:
This code runs when game are dispatched and  more players are connect then the amount needed to fill them.

_**The problem with line 1350:**_
- If GROUP_SIZE = 2 and POOL_SIZE = 3 in waitingroom.settings.js, nPlayers will probably equal 3 when games are dispatch. 
- This means that numberOfGames = 1 and groupSize = 2.
- On line 1338 nPlayersToDispatch is set to 2.
- On line 1350 no sorting will occur because nPlayersToDispatch equals groupSize. 
- Line 1404 runs anyways.


The DOC makes it seem like sorting would happen on line 1404. It says that sorting should occur when nPlayers > groupSize.

**Comment by shakty** [comment]
Thanks for the clarification, it makes sense now. I feel the documentation is correct, but the code isn't, so I am marking it as a bug . 

The fix should be changing line 1350 this way:
```js
// Old line
// if (nPlayersToDispatch > groupSize) {
// New line
if (nPlayers > groupSize) {
```
Am I right? If so, do you want to make a Pull Request and becoming a contributor?
