### ISSUE TITLE
Memory Database: Intro WIKI invalid code example

### ISSUE THREAD

**Issue by TVGG** [nodeGame/nodegame#171]
In the wiki for Memory Database: Intro the Manual insert (logic-side) section has invalid code. The following stage key value pairs are missing a colon : stage 2 and round 1

`// Logic.`
`memory.add({`
 `  player: 'B',`
 ` stage: { stage 2, step: 1, round 1}`
  `value: 3`
`});`
`memory.size(); // 5 (4 items from previous examples, and 1 new one).`

should be 
`// Logic.`
`memory.add({`
  `  player: 'B',`
   ` stage: { stage: 2, step: 1, round: 1}`
  `  value: 3`
`});`
`memory.size(); // 5 (4 items from previous examples, and 1 new one).`

**Comment by shakty** [comment]
Thanks for the report! Fixed. Feel free to change the wiki yourself if find more of such errors!
