### ISSUE TITLE
Git Pre-commit hook should print which line is longer than 80 chars

### ISSUE THREAD

**Issue by shakty** [nodeGame/nodegame#3]
As title.
By the way, I modified the limit from 81 to 82 chars, because the new line also counts as a character, and we don't care

**Comment by shakty** [comment]
by the way, I also removed the directory build from the checkings. Sometimes it contains third party library as well and it is impossible to guarantee the requirements

**Comment by benedek93** [comment]
Changed limit back to 81 (newline wasn't counted), added the line numbers.
