### ISSUE TITLE
Proposed enhancement: real-time (or after each round) communication between players?

### ISSUE THREAD

**Issue by lieuzhenghong** [nodeGame/nodegame#97]
I am interested in running games with natural-language or abstract communication between players. There's prior work on this: see [Restricted and free-form cheap-talk in the one-shot Stag Hunt game](https://ideas.repec.org/a/eee/gamebe/v109y2018icp294-310.html) (Dugar and Shahriar 2016), and Embrey et al. (2013) [An Experimental Study of Imperfect Public Monitoring: Efficiency versus Renegotiation-Proofness](http://people.cess.fas.nyu.edu/frechette/print/Embrey_2013a.pdf).

Possibly interesting might also be allowing communication between rounds of the fuzzy public good games ran by Nax, Balietti, Murphy and Helbing. [Adding noise to the institution: an experimental welfare investigation of the contribution-based grouping mechanism](https://link.springer.com/article/10.1007/s00355-017-1081-5).

What I'm envisioning is either something like a "chat room" between rounds for natural language communication. Would this be of interest as a proposed enhancement?

**Comment by shakty** [comment]
Hi lieuzhenghong,

There is already a Chat widget, but it could be improved of course. See here:

https://github.com/nodeGame/nodegame/wiki/Chat-Widget-v5

Does it fit your needs? If not we can discuss possible enhnancements.

**Comment by lieuzhenghong** [comment]
Thanks for the link! It's perfect. Something else I'm interested in is restricting the message space. But this shouldn't be too hard.

I'll have a play around with this and will update if any enhancements come to mind.

**Comment by shakty** [comment]
Ok, will close this issue in a couple of days if nothing new happens. Feel free to open a new one then.

**Comment by shakty** [comment]
I am closing this, just feel free to re-open this or a new one for feedback or comments.
